Refactor key content
eea/volto-eea-design-system pull request #126
Opened 2022-03-29 12:36 UTC by g-stamatis

2022-03-31 15:12 UTC, g-stamatis commented
[R3] Key content (messages)
https://taskman.eionet.europa.eu/issues/147635

2022-04-07 11:55 UTC, avoinea requested changes

2022-04-07 11:55 UTC, avoinea commented on theme/themes/eea/extras/publicationCard.less
>  .eea.publication.card {
@g-stamatis Is this file changes related to this PR?

2022-04-07 11:55 UTC, avoinea commented on src/ui/KeyContent/KeyContent.jsx
> +    <div className="eea key-content" {...rest}>
@g-stamatis To be HTML semantically correct, I think the output should be an unordered list `ul` `li`

See, for example: https://www.eea.europa.eu/publications/status-of-air-quality-in-Europe-2022

2022-04-14 07:09 UTC, avoinea approved these changes

2022-04-14 07:23 UTC, merged