Feature button enh
eea/volto-eea-design-system pull request #127
Opened 2022-03-29 12:45 UTC by g-stamatis

2022-03-29 19:19 UTC, ichim-david requested changes
@g-stamatis  I had to make a commit at line 90 to add .ui instead of ui.
You need to better check your selectors to ensure you don't have these kinds of
mistakes

2022-03-29 19:19 UTC, ichim-david commented on theme/themes/eea/elements/button.overrides
> +    font-size: 1.5rem;
Add this value as a variable

2022-03-29 19:19 UTC, ichim-david commented on theme/themes/eea/elements/button.overrides
> +  padding-right: 3em !important; // to apply to theme button paddings - button.less:856
Add this value as a variable

2022-03-29 19:19 UTC, ichim-david commented on theme/themes/eea/elements/button.overrides
> +  padding-left: 3em !important; // to apply to theme button paddings - button.less:856
Add this value as a variable

2022-03-29 19:19 UTC, ichim-david commented on theme/themes/eea/elements/button.overrides
> +  &.icon.button i {
any button should have the ability to add an icon not just the secondary, move this rule to the .ui.button basic style

2022-03-31 15:13 UTC, g-stamatis commented
[R3] Ask your questions
https://taskman.eionet.europa.eu/issues/147638

2022-05-05 13:27 UTC, g-stamatis commented
Included in buttons.

2022-05-05 13:27 UTC, closed without merging