[R2] Header
eea/volto-eea-design-system pull request #232
Opened 2022-09-02 08:52 UTC by g-stamatis

https://taskman.eionet.europa.eu/issues/147798

2022-09-02 08:52 UTC, g-stamatis commented
@eea-jenkins build storybook

2022-09-12 13:29 UTC, tarantilis commented
Didn't manage to use a "helper type solution" with callback as we had for other components, had hard time with the refs and triggers.
Since we had one occurrence with this bug, I used onClick function to stop propagation.
Works well, if there is a need to find a more global way to prevent multiple dropdowns we look at it again

2022-09-14 17:29 UTC, ichim-david requested changes

2022-09-14 17:29 UTC, ichim-david commented on theme/themes/eea/extras/header.less
> +      width: 18px;
@tarantilis add the values in variables

2022-09-15 10:42 UTC, tarantilis commented
@eea-jenkins build storybook

2022-09-15 10:52 UTC, tarantilis commented
@eea-jenkins build storybook

2022-09-16 17:21 UTC, ichim-david approved these changes
@tarantilis  I will merge this pull request however I think another pull request will be needed after we clarify the font size of the language dropdown

2022-09-16 17:22 UTC, merged