Updates on color palette
eea/volto-eea-design-system pull request #234
Opened 2022-09-06 11:59 UTC by tarantilis

https://taskman.eionet.europa.eu/issues/153269

Updates on link colors based on latest docusaurus update

2022-09-06 12:01 UTC, tarantilis commented
@eea-jenkins build storybook

2022-09-08 08:08 UTC, ichim-david requested changes

2022-09-08 08:08 UTC, ichim-david commented on theme/themes/eea/globals/site.variables
> +@linkVisitedColor    : @blue-3;
visited color is not accessible, I've added a comment in the ticket and we should get a new proposal from Manthos

2022-09-08 08:09 UTC, ichim-david commented
@g-stamatis  @tarantilis  see https://taskman.eionet.europa.eu/issues/153269#note-38

2022-09-14 17:24 UTC, ichim-david commented
@g-stamatis check the ticket feedback, visited color has change and will need to be reflected in this pull request

2022-09-15 12:02 UTC, tarantilis commented
@eea-jenkins build storybook

2022-09-15 16:43 UTC, merged