(feat): Make menu aware of pathname
eea/volto-eea-design-system pull request #336
Opened 2023-04-11 13:14 UTC by dobri1408

2023-04-12 06:34 UTC, dobri1408 commented
@eea-jenkins build storybook

2023-04-12 10:04 UTC, avoinea requested changes

2023-04-12 10:04 UTC, avoinea commented on src/ui/Header/Header.jsx
> +    if (!pathname.split('/').slice(2).join('/')) {
@dobri1408
1. I think this will crash if the pathname is null or undefined
2. Not all websites will have a language root `/en/`

2023-04-20 16:52 UTC, ichim-david approved these changes

2023-04-20 16:54 UTC, merged