[R2] Tab refactoring
eea/volto-eea-design-system pull request #406
Opened 2023-11-01 08:52 UTC by tarantilis

new PR for the old Tab task
https://taskman.eionet.europa.eu/issues/147811

2023-11-01 09:27 UTC, tarantilis commented
@eea-jenkins build storybook

2023-11-01 11:33 UTC, g-stamatis commented
@eea-jenkins build storybook

2023-11-01 11:46 UTC, g-stamatis commented
@eea-jenkins build storybook

2023-11-01 13:23 UTC, valentinab25 commented
@eea-jenkins build storybook

2023-11-01 14:04 UTC, valentinab25 commented
@eea-jenkins build all

2023-11-01 14:11 UTC, valentinab25 commented
@eea-jenkins build all

2023-11-09 10:42 UTC, tarantilis commented
@eea-jenkins build storybook

2023-11-13 15:39 UTC, ichim-david requested changes
@tarantilis I am having problems trying this branch as I get the tab story unresponsive when I switch to the tab accordion story. I expect that it doesn't like something from the withResize hoc and it's called too many times.  Tomorrow I can demo this issue which prevents me from properly accepting this work

2025-01-30 16:31 UTC, closed without merging